# docker-compose.yml
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - "../config_files/configs/:/bin/app/configs"
      - "../log/web:/bin/app/log"
    depends_on:
      - db
nginx:
    image: nginx
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "80:80"
    volumes:
      - "../config_files/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "../log/nginx:/var/log/nginx"
    depends_on:
      - web
db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: 1111
      MYSQL_DATABASE: stock_foilo_test
    volumes:
      - db_data:/var/lib/mysql
      
volumes:
  db_data: